### ISSUE TITLE
Support for alter database statement

### ISSUE THREAD

**Issue by fujin** [cloudspannerecosystem/spanner-schema-diff-tool#10]
I have an empty Spanner database ([created with Terraform](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database#version_retention_period)) which, during creation, is creating a DDL like this:

```
ALTER DATABASE test SET OPTIONS (
  version_retention_period = '7d'
);
```

When I run the diff tool, I get an error here:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported statement type: alter_database_statement
	at com.google.cloud.solutions.spannerddl.diff.DdlDiff.separateTablesIndexesConstraints(DdlDiff.java:539)
	at com.google.cloud.solutions.spannerddl.diff.DdlDiff.build(DdlDiff.java:483)
	at com.google.cloud.solutions.spannerddl.diff.DdlDiff.main(DdlDiff.java:638)
```

As far as I can tell, the tool doesn't allow for a non-default version_retention_period to be set via ALTER DATABASE, as it cannot parse the ALTER DATABASE statement.

We have two potential workarounds and wanted to know your input:
* Text process the input ddl to remove the ALTER DATABASE
* Implement the alter_database_statement so parsing works, make it noop? Or actually support ALTER DATABASE settings.

**Comment by zhiwei-arbo** [comment]
jfyi for anyone looking at this, in my own fork I made it a no-op [here](https://github.com/cloudspannerecosystem/spanner-schema-diff-tool/blob/main/src/main/java/com/google/cloud/solutions/spannerddl/diff/DdlDiff.java#L505)

It also seems possible to parse it by creating the relevant ASTXXX files, but I don't have such a use case yet
