### ISSUE TITLE
report a bug for change stream

### ISSUE THREAD

**Issue by iceriver123** [cloudspannerecosystem/spanner-schema-diff-tool#156]
Even though there is no change in the stream options, the diff tool outputs the following: 

ALTER CHANGE STREAM <Name> SET OPTIONS (null);

This error cannot be found when running the "mvn clean verify" command, but it appears when running the jar file again two DDLs file.

**Comment by iceriver123** [comment]
Ok. found the reason. it occurs when the options in new and old change streams are in different order 

such as old.ddl

create change stream toremain2 for all
OPTIONS (
retention_period = '7d',
value_capture_type = 'OLD_AND_NEW_VALUES',
exclude_ttl_deletes = true);

new.ddl

create change stream toremain2 for all
OPTIONS (
value_capture_type = 'OLD_AND_NEW_VALUES',
retention_period = '7d',
exclude_ttl_deletes = true);

The fix is easy

**Comment by nielm** [comment]
Thanks for the debugging - and fix!
