### ISSUE TITLE
Support For Change Streams

### ISSUE THREAD

**Issue by rob-pomelo** [cloudspannerecosystem/spanner-schema-diff-tool#9]
Hi! It would be great to support [Spanner Change Streams](https://cloud.google.com/spanner/docs/change-streams). We use this in a CI pipeline and the addition of change streams has broken our flow.

Even a way to simply ignore the change stream (and handle via manual DDL) would be a great starting point.

Thank you!

**Comment by zhiwei-arbo** [comment]
+1. In my own fork we changed it to not throw an error for some known exceptions when we encounter a `ParseException`, but it'd still be good if we can handle this.

@nielm any idea if it's possible to make the Parser support this? Not sure where we could get the tokens / we can manually add it into the jjtree files somehow?
